### ISSUE TITLE
figure out how to host images

### ISSUE THREAD

**Issue by diananova** [MLH-Fellowship/freebay#12]
- images can't be hosted on Django/Heroku
- ask @gmelodie

**Comment by gmelodie** [comment]
[No way to persist images on Heroku](https://stackoverflow.com/questions/24642967/can-i-host-images-in-heroku-or-do-i-need-s3). Perhaps try using [Amazon's S3](https://aws.amazon.com/s3/getting-started/?nc1=h_ls). @flosincapite any easier alternatives?
